replace my simple ssh-copy-id-2 script with a modified one from Centos 5.6

diff --git a/bin/ssh-copy-id-2 b/bin/ssh-copy-id-2
--- a/bin/ssh-copy-id-2
+++ b/bin/ssh-copy-id-2
@@ -1,17 +1,51 @@
-#!/bin/sh                                                                                                                                            
-KEY="$HOME/.ssh/id_rsa.pub"
+#!/bin/sh
 
-if [ ! -f $KEY ];then                                                                                                                                
-    echo "private key not found at $KEY"                                                                                                             
-    echo "* please create it with \"ssh-keygen -t rsa\" *"                                                                                           
-    exit                                                                                                                                             
-fi                                                                                                                                                   
-                                                                                                                                                     
-if [ -z $1 ];then                                                                                                                                    
-    echo "Usage: $0 username@host"                                                                                                                       
-    exit                                                                                                                                             
-fi                                                                                                                                                   
-                                                                                                                                                     
-echo "Putting your key on $1... "                                                                                                                    
-ssh -q $* "umask 0077; mkdir -p ~/.ssh ; echo "`cat $KEY`" >> ~/.ssh/authorized_keys"                                                                
-echo "done!"    
+# Shell script to install your identity.pub on a remote machine
+# Takes the remote machine name as an argument.
+# Obviously, the remote machine must accept password authentication,
+# or one of the other keys in your ssh-agent, for this to work.
+# This is from a Centos 5.6 box
+
+if [ "$#" -lt 1 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
+  echo "Usage: $0 [-i [identity_file]] [user@]machine" >&2
+  exit 1
+fi
+
+ID_FILE="${HOME}/.ssh/id_rsa.pub"
+
+if [ "-i" = "$1" ]; then
+  shift
+  # check if we have 2 parameters left, if so the first is the new ID file
+  if [ -n "$2" ]; then
+    if expr "$1" : ".*\.pub" ; then
+      ID_FILE="$1"
+    else
+      ID_FILE="$1.pub"
+    fi
+    shift         # and this should leave $1 as the target name
+  fi
+else
+  if [ x$SSH_AUTH_SOCK != x ] ; then
+    GET_ID="$GET_ID ssh-add -L"
+  fi
+fi
+
+if [ -z "`eval $GET_ID`" ] && [ -r "${ID_FILE}" ] ; then
+  GET_ID="cat ${ID_FILE}"
+fi
+
+if [ -z "`eval $GET_ID`" ]; then
+  echo "$0: ERROR: No identities found" >&2
+  exit 1
+fi
+
+{ eval "$GET_ID" ; } | ssh $1 "umask 077; test -d .ssh || mkdir .ssh ; cat >> .ssh/authorized_keys" || exit 1
+
+cat <<EOF
+Now try logging into the machine, with "ssh '$1'", and check in:
+
+  .ssh/authorized_keys
+
+to make sure we haven't added extra keys that you weren't expecting.
+
+EOF
